apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ps-ks8-ingress
spec:
  ingressClassName: azure-application-gateway
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: ps-products-service
                port:
                  number: 80
          - path: /nginx(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: ps-nginx-service
                port:
                  number: 80
          - path: /(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: ps-products-service
                port:
                  number: 80
